name: hoko_pipeline
version: 0.0.1
description: General responsibility chain implementation
homepage: https://github.com/HokoFly/hoko-pipeline-dart
environment:
  sdk: '>=2.10.0 <3.0.0'
dev_dependencies:
  test: ^1.16.7